"""Initial Migration2

Revision ID: c372b2d9e930
Revises: 25635ea6fc02
Create Date: 2024-11-22 18:11:27.680917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c372b2d9e930'
down_revision = '25635ea6fc02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signature', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    # ### end Alembic commands ###
